--- 
- name: Prepare basic env for php apps on all nodes
  hosts: vagrant
  remote_user: vagrant
  connection: local
  become: yes
  become_method: sudo
  roles:
    - tools
    - apache
    - php5.6
    - zookeeper
    - mysql
    - composer
    - project
