---
- name: Create apache2 configuration
  template:
    src: vhost-configuration.js2
    dest: /etc/apache2/sites-available/{{ project_name }}-configuration.conf

- name: Enable apache2 vhosts
  file:
    src: /etc/apache2/sites-available/{{ project_name }}-configuration.conf
    dest: /etc/apache2/sites-enabled/{{ project_name }}-configuration.conf
    state: link
  notify: restart apache



