parameters:
    secret_key: SecretToken
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     news-app
    database_user:     root
    database_password: rootpassword
    kafka_host: 10.0.0.201
    kafka_timeout: 3000
    kafka_port: 2181
    kafka_topic: test

framework:
    secret: '%secret_key%'
    form: ~
    assets: ~
    templating:
        engines: ['twig']
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

jms_serializer:
    metadata:
        auto_detection: true

fos_rest:
    param_fetcher_listener: true
    service:
        serializer: jms_serializer.serializer
    serializer:
        serialize_null: true
    routing_loader:
        default_format: json
    view:
        view_response_listener: 'force'
        serialize_null: true
        formats:
            json: true
            xml:  true