show:
  path:     /{id}
  defaults: { _controller: NewsBundle:News:show}
  methods: [GET]
  requirements:
      id: '\d+'

create:
  path:     /create
  defaults: { _controller: NewsBundle:News:create}
  methods: [POST]