---
- name: Install python-pycurl
  apt: pkg=python-pycurl state=latest

- name: Add PHP repo
  apt_repository: repo="ppa:ondrej/php"

- name: Install PHP
  apt: name=php7.0 state=latest force=yes

- name: Intsall PHP packages
  apt: name={{ item }} state=latest force=yes
  with_items:
    - php7.0-cli
    - php7.0-gd
    - php7.0-mysql
    - php7.0-curl
    - php7.0-mcrypt
    - php7.0-dev
    - php-pear
    - php7.0-fpm
    - php7.0-mbstring

- name: Configure PHP
  template: src=php_config.ini.j2 dest=/etc/php/7.0/fpm/conf.d/php_config.ini force=yes



