---

- name: Add repository for MySQL 5.7
  apt_repository: repo='ppa:ondrej/mysql-5.7'

- name: Set MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_pass | quote}}' vtype='password'

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_pass | quote}}' vtype='password'

- name: Install Mysql package
  apt: name={{ item }} state=installed
  with_items:
   - mysql-server
   - python-mysqldb
   - python-selinux

- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent" login_password="{{ mysql_pass }}" login_user=root

- name: Secures the MySQL root user
  mysql_user: user="root" password="{{ mysql_pass }}" host="{{ item }}" login_password="{{mysql_pass}}" login_user=root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1

- name: Removes the MySQL test database
  mysql_db: db=test state=absent login_password="{{ mysql_pass }}" login_user=root

